version: '1'
services:
  web:
    image: web:latest
    ports:
      - "8080:8080"
    depends_on:
      - login
      - gateway
  gateway:
    image: gateway:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5020:5020
  login:
    image: login:latest
    ports:
      - "5432:5432"