apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutorial-deployment
spec:
  selector:
    matchLabels:
      app: tutorial
  template:
    metadata:
      labels:
        app: tutorial
    spec:
      containers:
      - name: tutorial
        image: sjo0911/tutorial:v4
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: MongoDbSettings__Host
            value: mongodb-service
          - name: MongoDbSettings__Password
            value: pass
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: tutorial-service
spec:
  type: LoadBalancer
  selector:
    app: tutorial
  ports:
  - port: 80
    targetPort: 80

