stages:
  - build
  - test

image: maven:3.3.9-jdk-8

build:
  stage: build
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/ .war
test:
  stage: test
  script:
    - mvn test
