FROM jboss/wildfly
COPY /EShopJsf/target/eshopjsf.war /opt/jboss/wildfly/standalone/deployments/
COPY /EShop/target/EShop.war /opt/jboss/wildfly/standalone/deployments/
EXPOSE 8080

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-Drm.port=$PORT", "-b", "0.0.0.0"]